name: Lint YAML

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install yamllint
        run: pip install --no-cache-dir yamllint
      - name: Run yamllint
        run: |
          yamllint .
